### ISSUE TITLE
Reproducable Example of Online Learning

### ISSUE THREAD

**Issue by rexdouglass** [david-matheson/rftk#5]
Would it possible to have either a example or a unit test demonstrating online learning? In all the examples I've seen so far (including the regression branch), the learner is exposed to one set of data and then predicts on one set. When I tried to fumble with my my own test, running fit twice seemed to just replace the model entirely.

learner = rftk.learn.create_one_stream_classifier()
x = np.array([[0],[1], [2], [3], [4]], dtype=np.float32)
classes = np.array([0,1,2,3,4], dtype=np.int32)
predictor = learner.fit(x=x, classes=classes,
                            bootstrap=False,
                            number_of_features=1,
                            number_of_splitpoints=10)
print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]

> > > [0 1 2 3 4]

x = np.array([[1], [2], [3], [4]], dtype=np.float32) #Now expose it to fewer classes
classes = np.array([1,2,3,4], dtype=np.int32)
predictor = learner.fit(x=x, classes=classes)
print predictor.predict(x=x).argmax(axis=1) #Should be [1 2 3 4]

> > > > [1 2 3 4]
# Now lets see if it remembers the 0 class from before

x = np.array([[0],[1], [2], [3], [4]], dtype=np.float32)
print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]

> > > > [1 1 2 3 4]
# Nope, either "stream" isn't actually streaming, or fit doesn't mean "partial fit" or I'm misunderstanding something else

**Comment by david-matheson** [comment]
I apologize for the lack of documentation.  It is on my todolist along with instructions on how to setup the best performing config (it's dependent on your data).  Until I have more time, I'll just help you get setup.

Your usage is correct but you're using an offline classifier (the onestream refers to something different).  Try using 

learner = rftk.learn.create_online_one_stream_classifier()

instead of 

learner = rftk.learn.create_one_stream_classifier()

If you're on the regression branch I suggest you try:

learner = rftk.learn.create_uber_learner( data_type='matrix', 
                                            extractor_type='axis_aligned', 
                                            prediction_type='classification', 
                                            number_of_trees=25,
                                            number_of_features=1,
                                            number_of_splitpoints=10,
                                            possion_number_of_features=True,
                                            split_type='constant_splitpoints', 
                                            constant_splitpoints_type='at_random_datapoints',
                                            streams_type='one_stream', 
                                            max_frontier_size=10000,
                                            tree_type='online',
                                            min_child_size_sum=2)

But for a real world application where you don't want to split too quickly also try:

learner = rftk.learn.create_uber_learner( data_type='matrix', 
                                            extractor_type='axis_aligned', 
                                            prediction_type='classification', 
                                            number_of_trees=25,
                                            number_of_features=1,
                                            number_of_splitpoints=10,
                                            possion_number_of_features=True,
                                            split_type='constant_splitpoints', 
                                            constant_splitpoints_type='at_random_datapoints',
                                            streams_type='one_stream', 
                                            max_frontier_size=10000,
                                            tree_type='online',
                                            min_child_size_sum=10)

**Comment by rexdouglass** [comment]
Sorry for the long delay in responding. Thank you for the examples and to confirm for others, here's a run of the second learner, demonstrating that it takes multiple runs to converge on the right splits.

> > > learner = rftk.learn.create_uber_learner( data_type='matrix', 
> > > ... extractor_type='axis_aligned', 
> > > ... prediction_type='classification', 
> > > ... number_of_trees=25,
> > > ... number_of_features=1,
> > > ... number_of_splitpoints=10,
> > > ... possion_number_of_features=True,
> > > ... split_type='constant_splitpoints', 
> > > ... constant_splitpoints_type='at_random_datapoints',
> > > ... streams_type='one_stream', 
> > > ... max_frontier_size=10000,
> > > ... tree_type='online',
> > > ... min_child_size_sum=10)  
> > > x = np.array([[0],[1], [2], [3], [4]], dtype=np.float32)
> > > classes = np.array([0,1,2,3,4], dtype=np.int32)
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [0 0 0 0 0]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [0 0 0 0 0]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [1 1 2 2 2]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [1 1 2 2 2]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [1 1 2 2 2]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [1 1 2 3 3]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [1 1 2 3 3]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [0 1 2 3 3]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [0 1 2 3 3]
> > > predictor = learner.fit(x=x, classes=classes)
> > > print predictor.predict(x=x).argmax(axis=1) #Should be [0 1 2 3 4]
> > > [0 1 2 3 4]
